/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sacgames_SACWrapper */

#ifndef _Included_com_sacgames_SACWrapper
#define _Included_com_sacgames_SACWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sacgames_SACWrapper
 * Method:    initialize
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_com_sacgames_SACWrapper_initialize
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     com_sacgames_SACWrapper
 * Method:    sac_step
 * Signature: ([DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_sacgames_SACWrapper_sac_1stepper
  (JNIEnv *, jclass, jdoubleArray, jdouble);
  
  
JNIEXPORT jdoubleArray JNICALL Java_com_sacgames_SACWrapper_input_1stepper
  (JNIEnv * je, jclass jc, jdoubleArray xinit_s, jdouble tinit, jdouble u_controller, jdouble user_input) ;

#ifdef __cplusplus
}
#endif
#endif
