/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sacgames_SACWrapper */

#ifndef _Included_com_sacgames_SACWrapper
#define _Included_com_sacgames_SACWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sacgames_SACWrapper
 * Method:    initialize
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_com_sacgames_SACWrapper_initialize2
  (JNIEnv *, jclass, jdouble, jdouble, jint);

/*
 * Class:     com_sacgames_SACWrapper
 * Method:    sac_step
 * Signature: ([DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_sacgames_SACWrapper_sac_1stepper2
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
